### PR TITLE
Merge master into xenial

### PR DESCRIPTION
**Pull request by mariogrip**

### CODE REVIEW

**Comment by NeoTheThird** [comment]
Let's wait for the CI results ;)

**Comment by mariogrip** [comment]
ci, why u no build

**Comment by Flohack74** [comment]
Ci says I am not configured? xD

**Comment by mariogrip** [comment]
it's here https://ci.ubports.com/blue/organizations/jenkins/ubports%2Fkeyboard-component/activity

**Comment by mariogrip** [comment]
lets just merge and see what happens

**Pull request merged**
