### PR TITLE
add Emoji as a layout

### PR DESCRIPTION
**Pull request by Fuseteam**
this pull request adds the emoji layout to the languages folder with a couple of modifications.
These modifications are allow switching to it to function like the symbols keyboard
this does **not** add an new interaction to actually switch to emoji nor does it remove emoji from the list of languages

feedback regarding what is needed to get this merged in is appreaciated

### CODE REVIEW

**Comment by Fuseteam** [comment]
@UniversalSuperBox feedback please (when you have time)

**Comment by Fuseteam** [comment]
this should make it possible to remove ubunut-keyboard-emoji as a package and still switch to the emoji keyboard from the language menu

**Comment by Fuseteam** [comment]
the mr to actually remove the old emoji "layout" is here: https://gitlab.com/ubports/core/seeds/ubuntu-touch/-/merge_requests/26

**Review by UniversalSuperBox — CHANGES_REQUESTED** [review]
Hmm. I installed this on an already-setup device, removed ubuntu-keyboard-emoji, and restarted the device. When trying to switch to the emoji layout from the Layouts button, I get the following message:

```
WARNING: file:///usr/share/maliit/plugins/com/ubuntu/KeyboardContainer.qml:86:5: QML QtObject: Binding loop detected for property "characterKeypadSource"
CRITICAL: Couldn't find word engine plugin for  "emoji"
```

I cannot test this PR further.

**Comment by UniversalSuperBox** [comment]
I was able to force the system to downgrade to the keyboard version that's expected by this PR (the ongoing rebuild should help that) and got the emoji keyboard running. However, my settings still include the old Emoji plugin, which won't load.

The Emoji layout can be switched to and works fine.

**Comment by UniversalSuperBox** [comment]
This is my current layout switcher

image

**Comment by Fuseteam** [comment]
that's weird it shouldn't show up anymore, it doesn't for me anyway. maybe i need to reset and retest

**Comment by Fuseteam** [comment]
hmm it is indeed still visible, i'm not sure what more i can do to remove it

**Comment by Fuseteam** [comment]
uhhh somehow the emoji layout entry is no longer visible on my device but i didn't touch the keyboard code, not sure if its a restart or something that fixed it

**Comment by Fuseteam** [comment]
As a control case i removed the emoji keyboard without installing the PR and rebooted


And its still listed...........

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your PR is now migrated to:
https://gitlab.com/ubports/core/lomiri-keyboard/-/merge_requests/N
However, you might not be able to push new code into it, as the branch resides in our repository. In case you need to update it, please open a new MR from your (new) fork. I don't have a better solution at the moment.

Sorry for your inconvenience.

**Pull request closed without merging**
