### PR TITLE
Keyboard_fr-ch.qml : minor changes

### PR DESCRIPTION
**Pull request by wilfridd**
Hi,
My suggestions :
CharKey "e" : "3" replaces "é" (extended) and "Ė" (extendedShifted)
commaKey : "'" replaces "\"" (extended, extendedShifted)
dotKey : "\"" replaces "," (extended, extendedShifted)

BR,
wilfridd

### CODE REVIEW

**Review by UniversalSuperBox — CHANGES_REQUESTED** [review]
Must be merged with #74, #75, and #76.

It appears that there are too many letters in the dot key `.`'s list of keys. I know that isn't your doing, but we might have a chance to fix that now.

In most layouts, the dot key is for most end-of-sentence punctuation (`!`, `?`) while the comma key is for most mid-sentence punctuation (`-`, `"`). I'm unsure of what is commonly used on the french-swiss keyboard, but this convention should be followed here. Could you reshuffle these layouts so they become roughly balanced? This will allow people with smaller screens to use the french-swiss layout.

Also, be sure to balance changes you make to these keys in the other layouts. If you change the extended layout of dotKey, for example, you must change it in the search, URL, and email layouts as well.

You can make more changes to these files directly in GitHub if you like, by clicking "Files changed," the three dots on the file you would like to edit, then "Edit file." When you're finished editing, select "Commit directly" before clicking Commit.

**Comment by UniversalSuperBox** [comment]
Hey @wilfridd, sorry for the wait. Do you think you've completed the changes in the review, is this ready for a new review?

**Comment by wilfridd** [comment]
Hi Dalton,

Nothing to add so far! 
It is ready for a new review

BR
W.

On Thu, 11 Jul 2019 14:33:33 -0700, Dalton Durst wrote:
> Hey @wilfridd, sorry for the wait. Do you think you've 
> completed the changes in the review, is this ready for a new 
> review?
>

--

**Comment by Flohack74** [comment]
@UniversalSuperBox we should merge this for OTA-11

**Review by UniversalSuperBox — APPROVED** [review]
From everything I can see, not being able to use this keyboard or the language myself, this and the other three PRs are proper. I'll squash all three of them into the main branch.

**Comment by UniversalSuperBox** [comment]
Will merge in https://github.com/ubports/keyboard-component/pull/87

**Pull request closed without merging**
