### PR TITLE
Add swiss-french (QWERTZ) keyboard layout

### PR DESCRIPTION
**Pull request by ghost**
Please feel free to review and correct errors, and thanks a lot for your awesome work !

### CODE REVIEW

**Comment by NeoTheThird** [comment]
Hey, so sorry, totally forgot to get back to you on this one. I'll check it out and i'm positive we can get it into OTA-3. Thanks! :)

**Comment by Flohack74** [comment]
I think we can merge this right away, its just adding files. Plus, I could not test it without actually having it built into devel ;)

**Comment by turanmahmudov** [comment]
https://github.com/ubports/ubuntu-touch/issues/374
https://github.com/ubports/ubuntu-touch/issues/373

**Comment by Flohack74** [comment]
@spartid the keyboard is now added to the xenial 16.04 devel channel. Can you check (from tomorrow) if it works as intended?

**Comment by ghost** [comment]
Hello,

As I already said, I'm really sorry but I'm not able to test it yet 
because I've returned to Fairphone Open OS. I will maybe test it, but I 
don't know when. Until then, thank you very much for support, and thumbs 
up for your great job !

Le 21.05.2018 16:51, Florian Leeber a écrit :

**Comment by Flohack74** [comment]
Ah sorry did not see this. We will try to test ourselves :D

**Comment by turanmahmudov** [comment]
Hello,
I tested Azerbaijani and Turkish keyboards. Both works as expected. Thanks.

**Pull request merged**
