### PR TITLE
Macedonian (MK) layout

### PR DESCRIPTION
**Pull request by boriseto**
I've created the layouts without testing, since I've just installed the UBports on my device and I'm with limited connectivity where I am located at the moment due to government restrictions because of the virus situation. Anyway, the layout should be okay the way it is committed since it's the most popular one used in other platforms as well.
Since it's based on the Serbian one (just edited the needed keys), it should be okay.

### CODE REVIEW

**Comment by Flohack74** [comment]
@UniversalSuperBox how did we deal with keyboards in the past, just merge them and see how this flies? Any testing before?

**Review by UniversalSuperBox — CHANGES_REQUESTED** [review]
An incorrect keyboard layout can cause the keyboard to fail to load, preventing the user from even changing the layout. So, yes, testing prior to merge is a requirement. :)

It appears that this PR is missing the required changes to put these files into an installable package. For an example of these changes, see the files inside the `debian/` directory at https://github.com/ubports/keyboard-component/pull/86/files.

After this is merged, we will need to add the new package to the appropriate seed at https://gitlab.com/ubports/core/seeds/ubuntu-touch, then rebuild the seeds. This will cause the keyboard to be installed to the image.

**Comment by boriseto** [comment]
Understandable, I'll get onto it when I'm going to get a better connection to setup an env to test ir out.

**Comment by boriseto** [comment]
I've made some changes but can't seem to install it on the device at the moment. Looked for some support on the telegram channel and will go through with it and the next PR would be when the keyboard has been fully tested.

**Pull request closed without merging**
