### PR TITLE
Add bépo layout

### PR DESCRIPTION
**Pull request by lebanale**
Add bépo layout

### CODE REVIEW

**Comment by lebanale** [comment]
Maybe some mistake, but should work

**Comment by lebanale** [comment]
Missing W key. I'll do that later.

**Comment by UniversalSuperBox** [comment]
There is no need to add the autocorrect file after https://github.com/ubports/keyboard-component/pull/86. Please only make the changes like you see in that pull request (minus the C++ changes, you don't need to do those again :) )

**Comment by Fuseteam** [comment]
pull request #93 is an example how to can take advantage of #86 :)

**Comment by UniversalSuperBox** [comment]
Hi @lebanale,

I know it's been a long time, but are you able to make the requested changes in this thread? I'd like to help, if you need some pointers I'm available on many chat platforms or anything else you like.

**Comment by UniversalSuperBox** [comment]
Hi @lebanale,

Since we haven't heard from you in a while, I'll close this PR. If you'd like to continue work, please comment here or get a hold of me elsewhere and I'll help you out. Thanks!

**Pull request closed without merging**
