### PR TITLE
Let ubuntu-keyboard-autopilot depend on autopilot-qt5 instead of libautopilot-qt

### PR DESCRIPTION
**Pull request by hummlbach**
See #73

### CODE REVIEW

**Comment by UniversalSuperBox** [comment]
Why is the target branch master?

**Comment by Flohack74** [comment]
Also, your branch name wins a trophy that did not exist until now...

**Comment by Fuseteam** [comment]
World's most descriptive branch name™

**Comment by hummlbach** [comment]
Fixed the target branch. Linked to issue.

**Comment by UniversalSuperBox** [comment]
With the target changed, the PR conflicts and it looks like you might have some commits you don't want in there. Could you recreate this PR against the xenial branch?

**Comment by Fuseteam** [comment]
was this commit ever recreated against xenial?

**Comment by dobey** [comment]
> was this commit ever recreated against xenial?

I think it is perhaps no longer relevant, after the upgrade to Qt 5.12.

**Comment by Fuseteam** [comment]
hmm perhaps

**Pull request closed without merging**
