### PR TITLE
Fixed theming for japanese layout

### LINKED ISSUE #62: Japanese keyboard layout does not honor theme settings
When a non-default theme for the on-screen keyboard is selected, the Japanese keyboard layout does not honor all of the color settings. The flickable keys remain white as in Ambience.

image

### PR DESCRIPTION
**Pull request by kugiigi**
Use correct variables to support the new OSK themes. Fixes #62

### CODE REVIEW

**Comment by dobey** [comment]
Seems like the commit should have a "fixes #62" in it, no? :)

Also, have a screenshot?

**Comment by kugiigi** [comment]
oops, you are right, so can we still tag that fix in this PR?

**Comment by kugiigi** [comment]
Here's a screenshot of OSK in "Just Black"
screenshot20190125_220535564
I don't know how to fix the commit comment 😅

**Review by dobey — APPROVED** [review]
Would be nice to have tests for these sorts of things as well, but I'm not sure how plausible that currently is with the OSK.

**Pull request merged**
