### PR TITLE
Updated Dutch keyboard translation

### PR DESCRIPTION
**Pull request by Vistaus**
🙂

### CODE REVIEW

**Comment by Fuseteam** [comment]
uuuhhh did you edit the translations directly in the po files?

**Comment by Vistaus** [comment]
No, I used Poedit (on Linux). And I updated the Dutch po file with the latest strings from the pot file using Poedit's "Update from pot file" feature.

**Comment by Fuseteam** [comment]
ohw hmm i was under the impression translation go throught https://translate.ubports.com/projects/ but seems i was a bit [underinformed](http://docs.ubports.com/en/latest/contribute/translations.html) thanks for the translation work :+1:

**Comment by Flohack74** [comment]
Well we missed some projects for translations. Good catch we will merge this and then add the whole keyboard stuff to Weblate ;)

**Review by dobey — APPROVED** [review]
Thanks!

**Comment by Vistaus** [comment]
No problem! :)

**Comment by dadandalive** [comment]
I confirm these translations are well present in OTA-16 (RC 2021-W10). Just a minor remark: the merged .po file (and the according UBports Weblate page) do not seem to contain all base language strings. Or at least this one: "Double-tap to exit selection mode" of qml/Keyboard.qml:351.

**Pull request merged**
