### PR TITLE
Fork of #86 (add dvorak layout support) to test it on device

### PR DESCRIPTION
**Pull request by tallero**
I am trying to complete the requested change to #86. 

I would like to test the results on-device.

As I read on #86 I can give

    sudo ubports-qa install PR-90

to rebuild and reinstall on device the packages involved in the numbered PR, so I am creating a new PR for my changes because I do not know exactly how to build and test directly on-device.

### CODE REVIEW

**Comment by tallero** [comment]
@UniversalSuperBox `ubports-qa` of course at some point invokes `apt-get`.

According to this answer on [askubuntu](https://askubuntu.com/questions/600065/consequences-of-using-apt-get-in-ubuntu-touch), upgrading any package in the system risks bricking the device through OTAs. 
Apparently, this can be avoided enabling r/w (which I already did temporarily).

So, I would like to know:
- OTAs are just `/` snapshots?
- Can I keep the system updated through `apt` or do I have to install new OTAs when they come out?

**Comment by UniversalSuperBox** [comment]
Yes, OTAs are a snapshot of a root filesystem of Ubuntu Touch at a point in time. There are also delta updates which take the differences between two of these snapshots and apply them, and those will cause the most problems for you with a modified system. Overall, though, it's rather unlikely that an OTA update will brick your device because you've made a modification. The bigger concern is that updates will overwrite the changes that you've made to the image. Also, we won't support an image that's been monkeyed with in some way. Our first step is always to have you run through the installer to overwrite any changes you've made.

If something does get broken by an update, there are two ways to recover:

1. If you have shell access, run `sudo system-image-cli -b 0`. Optionally add `--progress=dots` so you get a progress output. This will download the latest full rootfs image and apply it.
1. Run the UBports Installer. It does the same thing, basically, just with a different computer to download it.

**Comment by UniversalSuperBox** [comment]
Also note that this is PR #90, so `PR-90` will do the installation for you.

**Comment by tallero** [comment]
>Also note that this is PR #90, so PR-90 will do the installation for you.

 Fixed; I am attaching the [failure log](https://github.com/ubports/keyboard-component/files/3552303/maliit-server.log). Apparently some of the files did not make it into the package.

There should be something in the build log.

**Comment by UniversalSuperBox** [comment]
Please let me know when you'd like another review, I'm not sure which of these commits are just trying things versus mergeable work. Thanks! :D

**Comment by tallero** [comment]
@UniversalSuperBox I tried the new (29/08) build just now. It works. The only problem I can see is that the name of the layout is still "en@dv", do not know why.

EDIT: Probably one has to add an entry to `languages.json` and all of these files:
https://github.com/ubports/keyboard-component/search?q=languages&unscoped_q=languages

**Comment by Fuseteam** [comment]
Do we still need this?

**Comment by dobey** [comment]
Closing this as #86 is merged.

**Pull request closed without merging**
