### PR TITLE
Changes in Spanish qmls to remove useless characters for Spanish languaje

### PR DESCRIPTION
**Pull request by J053Fabi0**

### CODE REVIEW

**Comment by J053Fabi0** [comment]
Why running `sudo ubports-qa install keyboard-component 120` gives me `CRITICAL:ubports-qa:Jenkins build not found`?

**Comment by dobey** [comment]
Shouldn't the `€` symbol remain in the layout? I'm pretty sure it's useful for Spain. :)

**Comment by J053Fabi0** [comment]
I'll change that. How can I test my pull request?

**Comment by dobey** [comment]
> I'll change that. How can I test my pull request?

I think it might need to be `ubports/keyboard-component` in the command line instead of just `keyboard-component` perhaps?

**Comment by J053Fabi0** [comment]
Well, it worked, but its trying to do an apt upgrade, which can't be done in UT, right? I tried remounting the system as read-write, but then it tells me there is no enough free space in /var/cache/apt/archives when the apt upgrade runs.
In my phone I have 52Gb of free space.

**Comment by Fuseteam** [comment]
you need to mount the /var/cache/apt to a different folder in home directory

**Comment by dobey** [comment]
> In my phone I have 52Gb of free space.

But this is not the size of the rootfs, which is limited due to how phones work. They are not like traditional PCs. You'll need to `sudo mount -t tmpfs tmpfs /var/cache/apt` which will use RAM to give enough space to download the packages. Also, you'll want to test on the `devel` channel instead of `stable` otherwise there will be way too many packages trying to be upgraded. If the repo was added you can just do `sudo apt-get update && sudo apt-get install ubuntu-keyboard` instead perhaps, rather than letting `ubports-qa` try to upgrade everything.

**Comment by J053Fabi0** [comment]
What do you guys think? The old one vs the new one:
### Old:
[](https://postimg.cc/34XZQP4N) 
### New:
[](https://postimg.cc/DWyhGTFk)

**Comment by Flohack74** [comment]
Did we forget this for OTA-13?

**Review by UniversalSuperBox — CHANGES_REQUESTED** [review]
How did all of the spacing changes happen here? It appears that the spacing model for the entire Keyboard.qml file was changed from 4 spaces to 2. Same for the es keyboards.

I'd suggest resubmitting this PR. In the resubmission, only make changes to the symbols and never the spacing of the files.

The readme change can be submitted in a separate PR too.

Resubmitting these changes will help us keep the keyboard code clean and readable for people who need to go back and fix bugs in the future.

**Comment by J053Fabi0** [comment]
Well, that's just too much work.

**Comment by Fuseteam** [comment]
oof

**Comment by Fuseteam** [comment]
@J053Fabi0 if you want we can help you with that

**Comment by J053Fabi0** [comment]
> @J053Fabi0 if you want we can help you with that

If you can do it, I would appreciate it. 🙏

**Comment by Fuseteam** [comment]
@J053Fabi0 great, the read update is no longer neccesary after the latest ubports-qa update btw

**Comment by UniversalSuperBox** [comment]
@Fuseteam, if you'd like to rewrite this PR to help it be merged, that'd be excellent. But in its current state, it cannot be merged. I'll close it for now, and we can open a new one with the proper changes.

Thank you!

**Comment by Fuseteam** [comment]
> @Fuseteam, if you'd like to rewrite this PR to help it be merged, that'd be excellent. But in its current state, it cannot be merged. I'll close it for now, and we can open a new one with the proper changes.
> 
> Thank you!

Alright understood i'll try and recreate the pr when i get the chance

**Pull request closed without merging**
