### PR TITLE
Added Bulgarian keyboard layout.

### PR DESCRIPTION
**Pull request by skrech**
Added Bulgarian (New Phonetic) keyboard layout.

### CODE REVIEW

**Comment by mariogrip** [comment]
Thank you :)

**Comment by Flohack74** [comment]
@skrech the keyboard is now added to the xenial 16.04 devel channel. Can you check (from tomorrow) if it works as intended?

**Comment by skrech** [comment]
It's working flawlessly! :)

**Comment by Talkless** [comment]
Isn't there missing line `ubuntu-keyboard-bulgarian` in `Package: ubuntu-keyboard-autopilot` definition? I see `bosnian` but there's no `bulgarian`. Ir this is by design?

**Comment by Flohack74** [comment]
Autopilot is only for testing. It should be all good in the main packaging manifest. Does it not work for you?

**Comment by Talkless** [comment]
No, just noticed inconsistency, that's all.

**Pull request merged**
