### PR TITLE
Update Keyboard Polish

### PR DESCRIPTION
**Pull request by Daniel20000522**

### CODE REVIEW

**Review by Flohack74 — CHANGES_REQUESTED** [review]
Why are you removing so many keybindings?

**Comment by Daniel20000522** [comment]
These characters are not used in Polish.

**Comment by Flohack74** [comment]
Can you send me a screenshot of a polish keyboard? I need to make sure we are doing the right thing.

**Comment by Daniel20000522** [comment]
screenshot20190822_233020698
screenshot20190822_233033102
screenshot20190822_233035968

**Comment by Flohack74** [comment]
I meant a screenshot of a real physical keyboard ;)

**Comment by Daniel20000522** [comment]
image20190822_233718563

**Comment by Daniel20000522** [comment]
We use such diacritical marks: ą, ć, ę, ł, ń, ó, ś, ź, ż

**Comment by Flohack74** [comment]
I see here: http://ascii-table.com/keyboard.php/457
So basically looks good, but if some Polish guys complain you have to fix it again. I can´t judge if this is 100% correct.

**Comment by Daniel20000522** [comment]
OK no problem.

**Review by Flohack74 — APPROVED** [review]

**Comment by advocatux** [comment]
Maybe this is a silly question (sorry) but is it somewhat possible that these changes are causing this issue https://github.com/ubports/ubuntu-touch/issues/1204? Thank you!

**Comment by Daniel20000522** [comment]
It is possible that this is a problem. I will revert the changes and see what happens.

**Comment by advocatux** [comment]
@Daniel20000522 just for the record, the Polish keyboard update affected that issue indirectly but the real culprit it seems it was how the apt pinning priorities were set.

See https://github.com/ubports/livecd-rootfs/issues/7#issuecomment-524466211 for details.

Thank you for your work !!

**Comment by UniversalSuperBox** [comment]
Hi @Daniel20000522,

Would you like a name other than `Daniel20000522` posted in the OTA-11 Call for Testing and Release blog post in the Changelog section? (for example: the end of https://ubports.com/blog/ubports-blog-1/post/ubuntu-touch-ota-10-release-239)

**Comment by Daniel20000522** [comment]
It can be the nick Daniel20000522. Thanks

**Comment by UniversalSuperBox** [comment]
Excellent, thank you. Huge thanks for the help!

**Comment by UniversalSuperBox** [comment]
Notes for QA:

The Polish keyboard has been changed to only include diacritics useful for the language. If you use this keyboard, please ensure that no characters you need have been removed.

**Comment by Daniel20000522** [comment]
Everything is OK. Thanks

**Comment by ziggutas** [comment]
Devices: Nexus 7 (flo), BQ E4.5 ubuntu edition. Both on rc (2019-W42)
On these two devices the Polish keyboard displays diacritical marks: ą, ć, ę, ł, ń, ó, ś, ź, ż.
There is no accent for d

**Comment by Daniel20000522** [comment]
What accent are you missing: ď, đ
These 2 marks do not belong to Polish diacritical marks so they have been removed.

**Comment by ziggutas** [comment]
OK, I understand. 
I don't know Polish so I was using the phone screenshots posted above as my point of reference.

**Pull request merged**
