### PR TITLE
All bengali translations

### PR DESCRIPTION
**Pull request by HackerShohag**
All bengali translations have been done.

### CODE REVIEW

**Comment by Fuseteam** [comment]
translations are normally done from https://translate.ubports.com/projects/ubports/keyboard-component/ so i'm not sure if this will be accepted

**Comment by HackerShohag** [comment]
@Fuseteam, Why not? Everything have been translated perfectly.

**Comment by Fuseteam** [comment]
I have just verified, it is fine. When it will be merged i have no idea

**Comment by HackerShohag** [comment]
Well then, will wait for it.

**Comment by Flohack74** [comment]
@HackerShohag sorry to say, but this will confuse our automatic translation system. Please use only https://translate.ubports.com. By the way, I dont think that Bengali can be selected as a phone´s language, so probably those translations will never appear in the GUI. Does it work?

**Comment by Fuseteam** [comment]
@Flohack74 eh? i thought you said it was fine.........

**Comment by HackerShohag** [comment]
@Flohack74 Although okay, no problem. I simply thought that if I could help.

**Comment by Fuseteam** [comment]
@HackerShohag you can via https://translate.ubports.com/projects/ubports/keyboard-component/, you can sign in with your github iirc

**Pull request closed without merging**
