### PR TITLE
Changes in UrlKey in  plugins/it/qml/Keyboard_it_url.qml

### PR DESCRIPTION
**Pull request by Aury88**
changed extended UrlKey  with more commons urls (maintain the alphabetical order and equivalence with Keyboard_it_url_search.qml)

### CODE REVIEW

**Review by NeoTheThird — COMMENTED** [review]
Is this a good idea? We don't have a seperate keyboard for swiss-italian, so maybe we shouldn't remove .ch for them. For san marino and the vatican, it's probably fine, the tld is short and the number of people affected by this is neglegible...

**Comment by NeoTheThird** [comment]
Let's take the opportunity to have it reviewed by an actual Italian guy ;)

**Comment by Aury88** [comment]
but I'm an actual Italian Guy xD

imho there should be an it(ch) keyboard or add only the .ch url, I think that also swiss-italian often use  .edu .org .net .int .gov urls

**Comment by sverzegnassi** [comment]
> but I'm an actual Italian Guy xD

Haha, blame that German guy above :P

> imho there should be an it(ch) keyboard or add only the .ch url, I think that also swiss-italian often use .edu .org .net .int .gov urls

Good point, that was my exact concern. However, I see we don't have regional layouts in our Ubuntu Touch images yet, despite there is e.g. a 'fr_ch' plugin available in the repository.

I'd suggest to replace the `.int` domain - which is less common, and it's not included in both iOS and Android - with `.ch` for the time being.
This way we would be able to release an OTA at any time, preventing potential disruptions for our Swiss users.

**Comment by sverzegnassi** [comment]
Btw, @NeoTheThird , is this PR proposed against the right branch? Do we currently use `master`, `vivid`, or `xenial`?

**Comment by mariogrip** [comment]
Xenial

**Comment by Aury88** [comment]
changed .int with .ch as suggested by @sverzegnassi.

**Comment by Aury88** [comment]
@mariogrip sorry Marius, I'm not very experienced  with all this. what have I to do?  have I to modify the  base to `xenial`? I see also `xenial-7.1-caf-sudoku`, `xenial_-_qt59` and `xenial_-_mir26`

**Comment by Aury88** [comment]
hi @sverzegnassi @NeoTheThird I don't know what happen but my PR was joint to other 21 commits in the xenial base....also this PR seems to fail the built check....where did I go wrong? what can I do?

**Comment by sverzegnassi** [comment]
@Aury88 I cherry-picked your commits and created a new PR. Your authorship has been preserved. Please check if everything is okay. 

Thanks again for the enhancement! I'm going to close this. Ref. #34

**Comment by Aury88** [comment]
@sverzegnassi Hi, and thank you for the explanation.

In the xenial branch of
 keyboard-component/plugins/it/qml/ 
I see the old urls (".com", ".ch", ".va", ".sm"  instead of ".ch", ".com", ".edu", ".org", ".net", ".gov")  
Could it be correlated with the "Closed with unmergend commits" warning?

not really care about my authorship preservation (especially for such a trivial patch xD) I was just worried about making a mess with the PR

**Pull request closed without merging**
