### PR TITLE
Pull up changes from xenial into edge

### PR DESCRIPTION
**Pull request by dobey**

### CODE REVIEW

**Comment by UniversalSuperBox** [comment]
I think I'd rather rebase the edge patches over the current state of xenial. Would you be okay with this?

**Comment by dobey** [comment]
> I think I'd rather rebase the edge patches over the current state of xenial. Would you be okay with this?

Wouldn't "rebase and merge" do this?

**Comment by UniversalSuperBox** [comment]
No, rebasing xenial onto edge would put these commits on top of the edge commits. I want to rebase edge onto xenial so we can merge cleanly later.

**Comment by dobey** [comment]
OK. It's fine by me, but I think it should merge cleanly either way, with "squash and merge" option.

**Pull request closed without merging**
